[project]
name = 'music-bird'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'
requirements = []
[contracts.music-bird]
path = 'contracts/music-bird.clar'
depends_on = ["nft-trait"]
clarity_version = 1
[contracts.nft-trait]
path = 'contracts/nft-trait.clar'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
